{% set name = "pyroute2" %}
{% set version = "0.6.11" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/p/pyroute2/pyroute2-{{ version }}.tar.gz
    sha256: 136346be66d552e4541d0679dbffac6b2e1237dfd39ee1a95062f850244917bd
    folder: pyroute2

  - url: https://pypi.io/packages/source/p/pyroute2.core/pyroute2.core-{{ version }}.tar.gz
    sha256: f4e77196cd658deee9502bb452485f40881b2f674e65092257527f9207e0c46c
    folder: pyroute2.core

  - url: https://pypi.io/packages/source/p/pyroute2.ethtool/pyroute2.ethtool-{{ version }}.tar.gz
    sha256: df116c2b9d16b67452f08984594e0791ef4d769d40b26e303c405f413d6b6175
    folder: pyroute2.ethtool

  - url: https://pypi.io/packages/source/p/pyroute2.ipdb/pyroute2.ipdb-{{ version }}.tar.gz
    sha256: 5133f92ee65b06e91f0e940f27e379645b4a185269a597e9b084a7b26f5e69bb
    folder: pyroute2.ipdb

  - url: https://pypi.io/packages/source/p/pyroute2.ipset/pyroute2.ipset-{{ version }}.tar.gz
    sha256: b887dc96b9b5b6e8d489c91de51e2ec831ef3c4c720b633d9a99b934b175aedb
    folder: pyroute2.ipset

  - url: https://pypi.io/packages/source/p/pyroute2.ndb/pyroute2.ndb-{{ version }}.tar.gz
    sha256: 8f3f79e9580ef59f593e5310a1b077e30774e0e83f5d5ec83fe279f21b5d93e6
    folder: pyroute2.ndb

  - url: https://pypi.io/packages/source/p/pyroute2.nftables/pyroute2.nftables-{{ version }}.tar.gz
    sha256: d921c01f81c171792709adab747935b3e8eef883799dd70b3c3f1d81219a82a5
    folder: pyroute2.nftables

  - url: https://pypi.io/packages/source/p/pyroute2.nslink/pyroute2.nslink-{{ version }}.tar.gz
    sha256: 47de27d5411c78e3265d76c20a482ae8dd892e7a767aa016e2ac1e229348d822
    folder: pyroute2.nslink

  - url: https://pypi.io/packages/source/p/pyroute2.minimal/pyroute2.minimal-{{ version }}.tar.gz
    sha256: bc0a5f6ceeea36548a0ee6559f8da4b8b0354cfe0244c848d04fd090704675ad
    folder: pyroute2.minimal

build:
  number: 0

requirements:
  host:
    - python
  run:
    - python

outputs:
  - name: pyroute2.core
    build:
      noarch: python
      script:
        - cd pyroute2.core
        - {{ PYTHON }} -m pip install --no-deps . -vv
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - psutil >=5.0
    test:
      imports:
        - pr2modules
        - pr2modules.bsd
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://github.com/svinota/pyroute2
      summary: 'Python Netlink library: the core'
      license: GPL-2.0-or-later OR Apache-2.0
      license_file:
        - LICENSE.GPL.v2
        - LICENSE.Apache.v2

  - name: pyroute2.ethtool
    build:
      noarch: python
      script:
        - cd pyroute2.ethtool
        - {{ PYTHON }} -m pip install --no-deps . -vv
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - pyroute2.core
    test:
      imports:
        - pr2modules
        # Import fails on Windows due to lack of fcntl
        # - pr2modules.ethtool
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://github.com/svinota/pyroute2
      summary: 'Python Netlink library: ethtool'
      license: GPL-2.0-or-later OR Apache-2.0
      license_file:
        - LICENSE.GPL.v2
        - LICENSE.Apache.v2

  - name: pyroute2.ipdb
    build:
      noarch: python
      script:
        - cd pyroute2.ipdb
        - {{ PYTHON }} -m pip install --no-deps . -vv
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - pyroute2.core
    test:
      imports:
        - pr2modules
        - pr2modules.ipdb
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://github.com/svinota/pyroute2
      summary: 'Python Netlink library: IPDB module'
      license: GPL-2.0-or-later OR Apache-2.0
      license_file:
        - LICENSE.GPL.v2
        - LICENSE.Apache.v2

  - name: pyroute2.ipset
    build:
      noarch: python
      script:
        - cd pyroute2.ipset
        - {{ PYTHON }} -m pip install --no-deps . -vv
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - pyroute2.core
    test:
      imports:
        - pr2modules
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://github.com/svinota/pyroute2
      summary: 'Python Netlink library: ipset'
      license: GPL-2.0-or-later OR Apache-2.0
      license_file:
        - LICENSE.GPL.v2
        - LICENSE.Apache.v2

  - name: pyroute2.ndb
    build:
      noarch: python
      entry_points:
        - pyroute2-cli = pr2modules.ndb.cli:run
      script:
        - cd pyroute2.ndb
        - {{ PYTHON }} -m pip install --no-deps . -vv
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - pyroute2.core
        - pyroute2.nslink
    test:
      imports:
        - pr2modules
        - pr2modules.cli
      commands:
        - pip check
        - pyroute2-cli --help
      requires:
        - pip
    about:
      home: https://github.com/svinota/pyroute2
      summary: 'Python Netlink library: NDB module'
      license: GPL-2.0-or-later OR Apache-2.0
      license_file:
        - LICENSE.GPL.v2
        - LICENSE.Apache.v2

  - name: pyroute2.nftables
    build:
      noarch: python
      script:
        - cd pyroute2.nftables
        - {{ PYTHON }} -m pip install --no-deps . -vv
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - pyroute2.core
    test:
      imports:
        - pr2modules
        - pr2modules.nftables
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://github.com/svinota/pyroute2
      summary: 'Python Netlink library: nftables'
      license: GPL-2.0-or-later OR Apache-2.0
      license_file:
        - LICENSE.GPL.v2
        - LICENSE.Apache.v2

  - name: pyroute2.nslink
    build:
      noarch: python
      script:
        - cd pyroute2.nslink
        - {{ PYTHON }} -m pip install --no-deps . -vv
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - pyroute2.core
    test:
      imports:
        - pr2modules
        - pr2modules.nslink
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://github.com/svinota/pyroute2
      summary: 'Python Netlink library: NetNS, NSPopen and remote modules'
      license: GPL-2.0-or-later OR Apache-2.0
      license_file:
        - LICENSE.GPL.v2
        - LICENSE.Apache.v2

  - name: pyroute2.minimal
    build:
      noarch: python
      script:
        - cd pyroute2.minimal
        - {{ PYTHON }} -m pip install --no-deps . -vv
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - pyroute2.core =={{ version }}
        - importlib-metadata
    test:
      imports:
        - pyroute2
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://github.com/svinota/pyroute2
      summary: 'Python Netlink library: minimal installation'
      license: GPL-2.0-or-later OR Apache-2.0
      license_file:
        - LICENSE.GPL.v2
        - LICENSE.Apache.v2

  - name: pyroute2
    build:
      noarch: python
      script:
        - cd pyroute2
        - {{ PYTHON }} -m pip install --no-deps . -vv
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - pyroute2.core =={{ version }}
        - pyroute2.ethtool =={{ version }}
        - pyroute2.ipdb =={{ version }}
        - pyroute2.ipset =={{ version }}
        - pyroute2.ndb =={{ version }}
        - pyroute2.nftables =={{ version }}
        - pyroute2.nslink =={{ version }}
        - importlib-metadata
    test:
      imports:
        - pyroute2
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://github.com/svinota/pyroute2
      summary: Python Netlink library
      license: GPL-2.0-or-later OR Apache-2.0
      license_file:
        - LICENSE.GPL.v2
        - LICENSE.Apache.v2

about:
  home: https://github.com/svinota/pyroute2
  summary: Python Netlink library
  license: GPL-2.0-or-later OR Apache-2.0
  license_file:
    - LICENSE.GPL.v2
    - LICENSE.Apache.v2

extra:
  feedstock-name: pyroute2
  recipe-maintainers:
    - nehaljwani
