{% set name = "pyroute2" %}
{% set version = "0.6.6" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/p/pyroute2/pyroute2-{{ version }}.tar.gz
    sha256: 0eac82c06f12d260fba6adb800541d1e83c7715f64efeb272b3d6841610a60b4
    folder: pyroute2

  - url: https://pypi.io/packages/source/p/pyroute2.core/pyroute2.core-{{ version }}.tar.gz
    sha256: ae5784d96b7afa84344bb61a2c8b5987db1cb848c75267548b325dc9d7e3a216
    folder: pyroute2.core

  - url: https://pypi.io/packages/source/p/pyroute2.ethtool/pyroute2.ethtool-{{ version }}.tar.gz
    sha256: 79ba78674517fdcd6482074c32defb2421b9b48d6a1f9ab7c15b990828826631
    folder: pyroute2.ethtool

  - url: https://pypi.io/packages/source/p/pyroute2.ipdb/pyroute2.ipdb-{{ version }}.tar.gz
    sha256: cb24891746d6a56a62674a047f09cc3f97c2918af95d2ba55e73c0930936d006
    folder: pyroute2.ipdb

  - url: https://pypi.io/packages/source/p/pyroute2.ipset/pyroute2.ipset-{{ version }}.tar.gz
    sha256: 93898ca5701021703bfb98a0e39fa7e70f3b77d150d147cc46ece0b64b9e2ff3
    folder: pyroute2.ipset

  - url: https://pypi.io/packages/source/p/pyroute2.ndb/pyroute2.ndb-{{ version }}.tar.gz
    sha256: 4dc8927740df3ab74831794f1062b3467446464582591d6dd2a678f0272dddee
    folder: pyroute2.ndb

  - url: https://pypi.io/packages/source/p/pyroute2.nftables/pyroute2.nftables-{{ version }}.tar.gz
    sha256: f35fc545af55d379dc776b840118d0d2ee0e5cbafd9093c4388c51f69957dd1c
    folder: pyroute2.nftables

  - url: https://pypi.io/packages/source/p/pyroute2.nslink/pyroute2.nslink-{{ version }}.tar.gz
    sha256: 5cc88050cf95a82db8cae786fcfa6fe654f4f114f969bbca6c3adf126f8eca51
    folder: pyroute2.nslink

  - url: https://pypi.io/packages/source/p/pyroute2.minimal/pyroute2.minimal-{{ version }}.tar.gz
    sha256: c39222d0d7c383dc7b2cee9be902ddb8fc0aeb53c061d984a444bc4db6a1c60d
    folder: pyroute2.minimal

build:
  number: 0

requirements:
  host:
    - python
  run:
    - python

outputs:
  - name: pyroute2.core
    build:
      noarch: python
      script:
        - cd pyroute2.core
        - {{ PYTHON }} -m pip install --no-deps . -vv
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - psutil >=5.0
    test:
      imports:
        - pr2modules
        - pr2modules.bsd
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://github.com/svinota/pyroute2
      summary: 'Python Netlink library: the core'
      license: GPL-2.0-or-later OR Apache-2.0
      license_file:
        - LICENSE.GPL.v2
        - LICENSE.Apache.v2

  - name: pyroute2.ethtool
    build:
      noarch: python
      script:
        - cd pyroute2.ethtool
        - {{ PYTHON }} -m pip install --no-deps . -vv
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - pyroute2.core
    test:
      imports:
        - pr2modules
        # Import fails on Windows due to lack of fcntl
        # - pr2modules.ethtool
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://github.com/svinota/pyroute2
      summary: 'Python Netlink library: ethtool'
      license: GPL-2.0-or-later OR Apache-2.0
      license_file:
        - LICENSE.GPL.v2
        - LICENSE.Apache.v2

  - name: pyroute2.ipdb
    build:
      noarch: python
      script:
        - cd pyroute2.ipdb
        - {{ PYTHON }} -m pip install --no-deps . -vv
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - pyroute2.core
    test:
      imports:
        - pr2modules
        - pr2modules.ipdb
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://github.com/svinota/pyroute2
      summary: 'Python Netlink library: IPDB module'
      license: GPL-2.0-or-later OR Apache-2.0
      license_file:
        - LICENSE.GPL.v2
        - LICENSE.Apache.v2

  - name: pyroute2.ipset
    build:
      noarch: python
      script:
        - cd pyroute2.ipset
        - {{ PYTHON }} -m pip install --no-deps . -vv
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - pyroute2.core
    test:
      imports:
        - pr2modules
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://github.com/svinota/pyroute2
      summary: 'Python Netlink library: ipset'
      license: GPL-2.0-or-later OR Apache-2.0
      license_file:
        - LICENSE.GPL.v2
        - LICENSE.Apache.v2

  - name: pyroute2.ndb
    build:
      noarch: python
      entry_points:
        - pyroute2-cli = pr2modules.ndb.cli:run
      script:
        - cd pyroute2.ndb
        - {{ PYTHON }} -m pip install --no-deps . -vv
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - pyroute2.core
        - pyroute2.nslink
    test:
      imports:
        - pr2modules
        - pr2modules.cli
      commands:
        - pip check
        - pyroute2-cli --help
      requires:
        - pip
    about:
      home: https://github.com/svinota/pyroute2
      summary: 'Python Netlink library: NDB module'
      license: GPL-2.0-or-later OR Apache-2.0
      license_file:
        - LICENSE.GPL.v2
        - LICENSE.Apache.v2

  - name: pyroute2.nftables
    build:
      noarch: python
      script:
        - cd pyroute2.nftables
        - {{ PYTHON }} -m pip install --no-deps . -vv
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - pyroute2.core
    test:
      imports:
        - pr2modules
        - pr2modules.nftables
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://github.com/svinota/pyroute2
      summary: 'Python Netlink library: nftables'
      license: GPL-2.0-or-later OR Apache-2.0
      license_file:
        - LICENSE.GPL.v2
        - LICENSE.Apache.v2

  - name: pyroute2.nslink
    build:
      noarch: python
      script:
        - cd pyroute2.nslink
        - {{ PYTHON }} -m pip install --no-deps . -vv
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - pyroute2.core
    test:
      imports:
        - pr2modules
        - pr2modules.nslink
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://github.com/svinota/pyroute2
      summary: 'Python Netlink library: NetNS, NSPopen and remote modules'
      license: GPL-2.0-or-later OR Apache-2.0
      license_file:
        - LICENSE.GPL.v2
        - LICENSE.Apache.v2

  - name: pyroute2.minimal
    build:
      noarch: python
      script:
        - cd pyroute2.minimal
        - {{ PYTHON }} -m pip install --no-deps . -vv
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - pyroute2.core =={{ version }}
        - importlib-metadata
    test:
      imports:
        - pyroute2
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://github.com/svinota/pyroute2
      summary: 'Python Netlink library: minimal installation'
      license: GPL-2.0-or-later OR Apache-2.0
      license_file:
        - LICENSE.GPL.v2
        - LICENSE.Apache.v2

  - name: pyroute2
    build:
      noarch: python
      script:
        - cd pyroute2
        - {{ PYTHON }} -m pip install --no-deps . -vv
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - pyroute2.core =={{ version }}
        - pyroute2.ethtool =={{ version }}
        - pyroute2.ipdb =={{ version }}
        - pyroute2.ipset =={{ version }}
        - pyroute2.ndb =={{ version }}
        - pyroute2.nftables =={{ version }}
        - pyroute2.nslink =={{ version }}
        - importlib-metadata
    test:
      imports:
        - pyroute2
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://github.com/svinota/pyroute2
      summary: Python Netlink library
      license: GPL-2.0-or-later OR Apache-2.0
      license_file:
        - LICENSE.GPL.v2
        - LICENSE.Apache.v2

about:
  home: https://github.com/svinota/pyroute2
  summary: Python Netlink library
  license: GPL-2.0-or-later OR Apache-2.0
  license_file:
    - LICENSE.GPL.v2
    - LICENSE.Apache.v2

extra:
  feedstock-name: pyroute2
  recipe-maintainers:
    - nehaljwani
